# Generated by Django 5.0.1 on 2024-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sprinc', models.CharField(max_length=100)),
                ('sloc', models.CharField(max_length=100)),
            ],
        ),
    ]
